### ISSUE TITLE
Dataset 2 untar error

### ISSUE THREAD

**Issue by ericqh** [ICT-MIRACLE-lab/CTPelvic1K#1]
When I tried to untar dataset2, the following error occurred. Does anyone run into this issue as well?

$ tar -xzvf CTPelvic1K_dataset2_data.tar.gz.0 CTPelvic1K_dataset2_data.tar.gz.1 CTPelvic1K_datas et2_data.tar.gz.2 CTPelvic1K_dataset2_data.tar.gz.3 CTPelvic1K_dataset2_data.tar.gz.4 CTPelvic1K_dataset2_data.tar.gz.5 CTPelvic1K_dataset2_data.tar.gz.6 CTPelvic1K_dataset2_data.tar.gz.7

tar: Truncated input file (needed 109287936 bytes, only 0 available)
tar: CTPelvic1K_dataset2_data.tar.gz.1: Not found in archive
tar: CTPelvic1K_dataset2_data.tar.gz.2: Not found in archive
tar: CTPelvic1K_dataset2_data.tar.gz.3: Not found in archive
tar: CTPelvic1K_dataset2_data.tar.gz.4: Not found in archive
tar: CTPelvic1K_dataset2_data.tar.gz.5: Not found in archive
tar: CTPelvic1K_dataset2_data.tar.gz.6: Not found in archive
tar: CTPelvic1K_dataset2_data.tar.gz.7: Not found in archive
tar: Error exit delayed from previous errors.

**Comment by EricKani** [comment]
You can try this command:

cat CTPelvic1K_dataset2_data.tar.gz.* | tar -zxv
