### ISSUE TITLE
Train/val/test split and provided model weights

### ISSUE THREAD

**Issue by duducheng** [ICT-MIRACLE-lab/CTPelvic1K#5]
Hi, 

Thank you for providing such an amazing dataset ;)

I would like to know how to compare with the provided nnUNet baseline. What's the exact dataset split? Could u provide the the data split-id correspondence so that we could compare our own method with your baseline model weights?

Cheers,
Jiancheng Yang

**Comment by EricKani** [comment]
Hi Jiancheng,

Thanks for your interest in our work, and I am very sorry for the late response.

I forget the account information which is used for creating this repository, so I uplod the file with 34 folds split information to the google drive .
(https://drive.google.com/file/d/1qb708KQtdknEcr2CM8PvJCLAVWuHa3dE/view?usp=sharing) 

Best,
Pengbo Liu
